
// This file has been generated by the GUI designer. Do not modify.
namespace ToonBoomExportGUI
{
	public partial class SceneExportList
	{
		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget ToonBoomExportGUI.SceneExportList
			global::Stetic.BinContainer.Attach(this);
			this.Name = "ToonBoomExportGUI.SceneExportList";
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
