
// This file has been generated by the GUI designer. Do not modify.
namespace ToonBoomExportGUI
{
	public partial class StartScreen
	{
		private global::Gtk.HBox hbox1;

		private global::Gtk.Button NewButton;

		private global::Gtk.Button OpenButton;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget ToonBoomExportGUI.StartScreen
			this.WidthRequest = 400;
			this.HeightRequest = 60;
			this.Name = "ToonBoomExportGUI.StartScreen";
			this.Title = global::Mono.Unix.Catalog.GetString("Toon Boom Exporter");
			this.TypeHint = ((global::Gdk.WindowTypeHint)(1));
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Resizable = false;
			this.AllowGrow = false;
			this.Gravity = ((global::Gdk.Gravity)(5));
			// Container child ToonBoomExportGUI.StartScreen.Gtk.Container+ContainerChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.NewButton = new global::Gtk.Button();
			this.NewButton.CanFocus = true;
			this.NewButton.Name = "NewButton";
			this.NewButton.UseUnderline = true;
			this.NewButton.Label = global::Mono.Unix.Catalog.GetString("New...");
			this.hbox1.Add(this.NewButton);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.NewButton]));
			w1.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.OpenButton = new global::Gtk.Button();
			this.OpenButton.CanFocus = true;
			this.OpenButton.Name = "OpenButton";
			this.OpenButton.UseUnderline = true;
			this.OpenButton.Label = global::Mono.Unix.Catalog.GetString("Open...");
			this.hbox1.Add(this.OpenButton);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.OpenButton]));
			w2.Position = 1;
			this.Add(this.hbox1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 587;
			this.DefaultHeight = 216;
			this.Show();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
			this.NewButton.Clicked += new global::System.EventHandler(this.NewClicked);
			this.OpenButton.Clicked += new global::System.EventHandler(this.OpenClicked);
		}
	}
}
