
// This file has been generated by the GUI designer. Do not modify.
namespace ToonBoomExportGUI
{
	public partial class ProjectWindow
	{
		private global::Gtk.UIManager UIManager;

		private global::Gtk.Action FileAction;

		private global::Gtk.Action OptionsAction;

		private global::Gtk.Action SetBinaryLocationAction;

		private global::Gtk.Action NewProjectAction;

		private global::Gtk.Action OpenProjectAction;

		private global::Gtk.Action SaveProjectAction;

		private global::Gtk.Action SaveProjectAsAction;

		private global::Gtk.Action ExitAction;

		private global::Gtk.Action ToolsAction;

		private global::Gtk.Action UTransformAction;

		private global::Gtk.Action Tvg2XmlAction;

		private global::Gtk.VBox Root;

		private global::Gtk.MenuBar menubar2;

		private global::Gtk.VPaned vpaned3;

		private global::Gtk.VBox vbox5;

		private global::Gtk.HButtonBox hbuttonbox3;

		private global::Gtk.Button AddXStageButton;

		private global::Gtk.Notebook Notebook;

		private global::Gtk.Label label4;

		private global::Gtk.HSeparator hseparator2;

		private global::Gtk.VBox vbox7;

		private global::Gtk.HSeparator hseparator3;

		private global::Gtk.HButtonBox hbuttonbox5;

		private global::Gtk.Button NewExportListButton;

		private global::Gtk.Notebook NotebookExport;

		private global::Gtk.Label label13;

		private global::Gtk.HBox hbox1;

		private global::Gtk.Button BuildButton;

		private global::Gtk.ToggleButton BuildObsolete;

		private global::Gtk.ProgressBar ProgressWidget;

		private global::Gtk.HButtonBox hbuttonbox4;

		private global::Gtk.HSeparator hseparator1;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget ToonBoomExportGUI.ProjectWindow
			this.UIManager = new global::Gtk.UIManager();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
			this.FileAction = new global::Gtk.Action("FileAction", global::Mono.Unix.Catalog.GetString("File"), null, null);
			this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString("File");
			w1.Add(this.FileAction, null);
			this.OptionsAction = new global::Gtk.Action("OptionsAction", global::Mono.Unix.Catalog.GetString("Options"), null, null);
			this.OptionsAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Options");
			w1.Add(this.OptionsAction, null);
			this.SetBinaryLocationAction = new global::Gtk.Action("SetBinaryLocationAction", global::Mono.Unix.Catalog.GetString("Set Binary Location..."), null, null);
			this.SetBinaryLocationAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Set Binary Location...");
			w1.Add(this.SetBinaryLocationAction, null);
			this.NewProjectAction = new global::Gtk.Action("NewProjectAction", global::Mono.Unix.Catalog.GetString("_New Project..."), null, null);
			this.NewProjectAction.ShortLabel = global::Mono.Unix.Catalog.GetString("_New Project...");
			w1.Add(this.NewProjectAction, null);
			this.OpenProjectAction = new global::Gtk.Action("OpenProjectAction", global::Mono.Unix.Catalog.GetString("_Open Project..."), null, null);
			this.OpenProjectAction.ShortLabel = global::Mono.Unix.Catalog.GetString("_Open Project...");
			w1.Add(this.OpenProjectAction, null);
			this.SaveProjectAction = new global::Gtk.Action("SaveProjectAction", global::Mono.Unix.Catalog.GetString("_Save Project"), null, null);
			this.SaveProjectAction.ShortLabel = global::Mono.Unix.Catalog.GetString("_Save Project");
			w1.Add(this.SaveProjectAction, null);
			this.SaveProjectAsAction = new global::Gtk.Action("SaveProjectAsAction", global::Mono.Unix.Catalog.GetString("Save Project _as..."), null, null);
			this.SaveProjectAsAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Save Project _as...");
			w1.Add(this.SaveProjectAsAction, null);
			this.ExitAction = new global::Gtk.Action("ExitAction", global::Mono.Unix.Catalog.GetString("Exit"), null, null);
			this.ExitAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Exit");
			w1.Add(this.ExitAction, null);
			this.ToolsAction = new global::Gtk.Action("ToolsAction", global::Mono.Unix.Catalog.GetString("Tools"), null, null);
			this.ToolsAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Tools");
			w1.Add(this.ToolsAction, null);
			this.UTransformAction = new global::Gtk.Action("UTransformAction", global::Mono.Unix.Catalog.GetString("UTransform"), null, null);
			this.UTransformAction.ShortLabel = global::Mono.Unix.Catalog.GetString("UTransform");
			w1.Add(this.UTransformAction, null);
			this.Tvg2XmlAction = new global::Gtk.Action("Tvg2XmlAction", global::Mono.Unix.Catalog.GetString("Tvg2Xml"), null, null);
			this.Tvg2XmlAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Tvg2Xml");
			w1.Add(this.Tvg2XmlAction, null);
			this.UIManager.InsertActionGroup(w1, 0);
			this.AddAccelGroup(this.UIManager.AccelGroup);
			this.Name = "ToonBoomExportGUI.ProjectWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("ProjectWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child ToonBoomExportGUI.ProjectWindow.Gtk.Container+ContainerChild
			this.Root = new global::Gtk.VBox();
			this.Root.Name = "Root";
			this.Root.Spacing = 6;
			// Container child Root.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString(@"<ui><menubar name='menubar2'><menu name='FileAction' action='FileAction'><menuitem name='NewProjectAction' action='NewProjectAction'/><separator/><menuitem name='OpenProjectAction' action='OpenProjectAction'/><separator/><menuitem name='SaveProjectAction' action='SaveProjectAction'/><menuitem name='SaveProjectAsAction' action='SaveProjectAsAction'/><separator/><menuitem name='ExitAction' action='ExitAction'/></menu><menu name='OptionsAction' action='OptionsAction'><menuitem name='SetBinaryLocationAction' action='SetBinaryLocationAction'/></menu></menubar></ui>");
			this.menubar2 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget("/menubar2")));
			this.menubar2.Name = "menubar2";
			this.Root.Add(this.menubar2);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.Root[this.menubar2]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child Root.Gtk.Box+BoxChild
			this.vpaned3 = new global::Gtk.VPaned();
			this.vpaned3.CanFocus = true;
			this.vpaned3.Name = "vpaned3";
			this.vpaned3.Position = 250;
			// Container child vpaned3.Gtk.Paned+PanedChild
			this.vbox5 = new global::Gtk.VBox();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbuttonbox3 = new global::Gtk.HButtonBox();
			this.hbuttonbox3.Name = "hbuttonbox3";
			this.hbuttonbox3.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(3));
			// Container child hbuttonbox3.Gtk.ButtonBox+ButtonBoxChild
			this.AddXStageButton = new global::Gtk.Button();
			this.AddXStageButton.CanFocus = true;
			this.AddXStageButton.Name = "AddXStageButton";
			this.AddXStageButton.UseUnderline = true;
			this.AddXStageButton.Label = global::Mono.Unix.Catalog.GetString("Add XStage File...");
			global::Gtk.Image w3 = new global::Gtk.Image();
			w3.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-add", global::Gtk.IconSize.Menu);
			this.AddXStageButton.Image = w3;
			this.hbuttonbox3.Add(this.AddXStageButton);
			global::Gtk.ButtonBox.ButtonBoxChild w4 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox3[this.AddXStageButton]));
			w4.Expand = false;
			w4.Fill = false;
			this.vbox5.Add(this.hbuttonbox3);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.hbuttonbox3]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.Notebook = new global::Gtk.Notebook();
			this.Notebook.CanFocus = true;
			this.Notebook.Name = "Notebook";
			this.Notebook.CurrentPage = 0;
			// Notebook tab
			global::Gtk.Label w6 = new global::Gtk.Label();
			w6.Visible = true;
			this.Notebook.Add(w6);
			this.label4 = new global::Gtk.Label();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("Placeholder");
			this.Notebook.SetTabLabel(w6, this.label4);
			this.label4.ShowAll();
			this.vbox5.Add(this.Notebook);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.Notebook]));
			w7.Position = 1;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hseparator2 = new global::Gtk.HSeparator();
			this.hseparator2.Name = "hseparator2";
			this.vbox5.Add(this.hseparator2);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.hseparator2]));
			w8.PackType = ((global::Gtk.PackType)(1));
			w8.Position = 2;
			w8.Expand = false;
			w8.Fill = false;
			this.vpaned3.Add(this.vbox5);
			global::Gtk.Paned.PanedChild w9 = ((global::Gtk.Paned.PanedChild)(this.vpaned3[this.vbox5]));
			w9.Resize = false;
			// Container child vpaned3.Gtk.Paned+PanedChild
			this.vbox7 = new global::Gtk.VBox();
			this.vbox7.Name = "vbox7";
			this.vbox7.Spacing = 6;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hseparator3 = new global::Gtk.HSeparator();
			this.hseparator3.Name = "hseparator3";
			this.vbox7.Add(this.hseparator3);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.hseparator3]));
			w10.Position = 0;
			w10.Expand = false;
			w10.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hbuttonbox5 = new global::Gtk.HButtonBox();
			this.hbuttonbox5.Name = "hbuttonbox5";
			this.hbuttonbox5.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(3));
			// Container child hbuttonbox5.Gtk.ButtonBox+ButtonBoxChild
			this.NewExportListButton = new global::Gtk.Button();
			this.NewExportListButton.CanFocus = true;
			this.NewExportListButton.Name = "NewExportListButton";
			this.NewExportListButton.UseUnderline = true;
			this.NewExportListButton.Label = global::Mono.Unix.Catalog.GetString("New Export List...");
			global::Gtk.Image w11 = new global::Gtk.Image();
			w11.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-new", global::Gtk.IconSize.Menu);
			this.NewExportListButton.Image = w11;
			this.hbuttonbox5.Add(this.NewExportListButton);
			global::Gtk.ButtonBox.ButtonBoxChild w12 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox5[this.NewExportListButton]));
			w12.Expand = false;
			w12.Fill = false;
			this.vbox7.Add(this.hbuttonbox5);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.hbuttonbox5]));
			w13.Position = 1;
			w13.Expand = false;
			w13.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.NotebookExport = new global::Gtk.Notebook();
			this.NotebookExport.CanFocus = true;
			this.NotebookExport.Name = "NotebookExport";
			this.NotebookExport.CurrentPage = 0;
			// Notebook tab
			global::Gtk.Label w14 = new global::Gtk.Label();
			w14.Visible = true;
			this.NotebookExport.Add(w14);
			this.label13 = new global::Gtk.Label();
			this.label13.Name = "label13";
			this.label13.LabelProp = global::Mono.Unix.Catalog.GetString("Placeholder");
			this.NotebookExport.SetTabLabel(w14, this.label13);
			this.label13.ShowAll();
			this.vbox7.Add(this.NotebookExport);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.NotebookExport]));
			w15.Position = 2;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.BuildButton = new global::Gtk.Button();
			this.BuildButton.CanFocus = true;
			this.BuildButton.Name = "BuildButton";
			this.BuildButton.UseUnderline = true;
			this.BuildButton.Label = global::Mono.Unix.Catalog.GetString("Build All");
			this.hbox1.Add(this.BuildButton);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.BuildButton]));
			w16.Position = 0;
			w16.Expand = false;
			w16.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.BuildObsolete = new global::Gtk.ToggleButton();
			this.BuildObsolete.CanFocus = true;
			this.BuildObsolete.Name = "BuildObsolete";
			this.BuildObsolete.UseUnderline = true;
			this.BuildObsolete.Label = global::Mono.Unix.Catalog.GetString("Build Obsolete");
			this.hbox1.Add(this.BuildObsolete);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.BuildObsolete]));
			w17.Position = 1;
			w17.Expand = false;
			w17.Fill = false;
			this.vbox7.Add(this.hbox1);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.hbox1]));
			w18.Position = 3;
			w18.Expand = false;
			w18.Fill = false;
			this.vpaned3.Add(this.vbox7);
			this.Root.Add(this.vpaned3);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.Root[this.vpaned3]));
			w20.Position = 1;
			// Container child Root.Gtk.Box+BoxChild
			this.ProgressWidget = new global::Gtk.ProgressBar();
			this.ProgressWidget.Name = "ProgressWidget";
			this.ProgressWidget.Text = global::Mono.Unix.Catalog.GetString("0 / 100 jobs");
			this.ProgressWidget.Fraction = 1D;
			this.Root.Add(this.ProgressWidget);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.Root[this.ProgressWidget]));
			w21.Position = 2;
			w21.Expand = false;
			w21.Fill = false;
			// Container child Root.Gtk.Box+BoxChild
			this.hbuttonbox4 = new global::Gtk.HButtonBox();
			this.hbuttonbox4.Name = "hbuttonbox4";
			this.Root.Add(this.hbuttonbox4);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.Root[this.hbuttonbox4]));
			w22.Position = 3;
			w22.Expand = false;
			w22.Fill = false;
			// Container child Root.Gtk.Box+BoxChild
			this.hseparator1 = new global::Gtk.HSeparator();
			this.hseparator1.Name = "hseparator1";
			this.Root.Add(this.hseparator1);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.Root[this.hseparator1]));
			w23.Position = 4;
			w23.Expand = false;
			w23.Fill = false;
			this.Add(this.Root);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 1201;
			this.DefaultHeight = 709;
			this.Show();
		}
	}
}
